---
name: Bump golang version 1.19

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 6'

permissions:
  contents: read

jobs:
  bump-1.19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/workflows/bump-golang
        with:
          branch: '1.19'
          go-minor: '1.19'
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
