---
name: Bump golang version 1.18

on:
  schedule:
    - cron: '0 21 * * 6'

permissions:
  pull-requests: write
  contents: write

jobs:
  bump-1.18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/workflows/bump-golang
        with:
          branch: '1.18'
          go-minor: '1.18'
          token: ${{ github.token }}
